name: gg_version
description: A dart package offering methods for consistent versioning of dart packages..
version: 1.3.0
repository: https://github.com/inlavigo/gg_version.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  checked_yaml: ^2.0.3
  gg_args: ^1.0.3
  gg_console_colors: ^2.0.0
  gg_git: ^2.0.0
  gg_log: ^1.0.0
  gg_process: ^1.1.0
  gg_status_printer: ^1.0.5
  http: ^1.2.1
  meta: ^1.12.0
  mocktail: ^1.0.3
  path: ^1.8.0
  pub_semver: ^2.1.4
  pubspec_parse: ^1.2.3
  yaml: ^3.1.2
  yaml_edit: ^2.2.0

dev_dependencies:
  gg_capture_print: ^1.0.3
  lints: ^3.0.0
  pana: ^0.22.2
  test: ^1.24.0
  recase: any
  gg_install_gg: ^1.0.1
