// @license
// Copyright (c) ggsuite
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import 'dart:io';

import 'package:gg_lang/gg_lang.dart';
import 'package:path/path.dart';

// #############################################################################
/// Marks a file as generated by `gg version write-version-file`.
///
/// Written into both the version file and its mirror test. The mirror test is
/// only regenerated when this marker is missing, which distinguishes a real
/// generated test from the boilerplate stub `gg_test` plants for any `lib/src`
/// file that has no test.
const String versionFileMarker = 'GENERATED BY gg_version WriteVersionFile';

// .............................................................................
/// The license header every generated Dart file starts with.
///
/// TypeScript files carry no header, matching the rest of the suite.
const String versionFileLicenseHeader = '''
// @license
// Copyright (c) ggsuite
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.''';

// .............................................................................
/// Converts a package name into the slug used for file names.
///
/// Strips an npm scope (`@scope/pkg` becomes `pkg`), lowercases, collapses
/// every run of non-alphanumeric characters into `_`, and trims leading and
/// trailing `_`. Falls back to `package` when nothing is left.
String versionFileSlug(String packageName) {
  var name = packageName.trim();

  if (name.startsWith('@')) {
    final slash = name.indexOf('/');
    if (slash >= 0) {
      name = name.substring(slash + 1);
    }
  }

  name = name.toLowerCase().replaceAll(RegExp('[^a-z0-9]+'), '_');
  name = name.replaceAll(RegExp(r'^_+'), '').replaceAll(RegExp(r'_+$'), '');

  return name.isEmpty ? 'package' : name;
}

// .............................................................................
/// Returns the name of the generated constant for [slug].
///
/// `gg_version` becomes `ggVersionVersion`. A slug starting with a digit is
/// letter-prefixed (`3d_utils` becomes `pkg3dUtilsVersion`) because an
/// underscore prefix would make the constant library-private in Dart and
/// therefore impossible to export.
String versionFileIdentifier(String slug) {
  final parts = slug.split('_').where((p) => p.isNotEmpty).toList();
  if (parts.isEmpty) {
    return 'packageVersion';
  }

  final camel = [
    parts.first,
    ...parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)),
  ].join();

  final safe = RegExp('^[0-9]').hasMatch(camel)
      ? 'pkg${camel[0].toUpperCase()}${camel.substring(1)}'
      : camel;

  return '${safe}Version';
}

// #############################################################################
/// Describes where a package's generated version file and its mirror test
/// live, and renders their contents.
///
/// One spec per language. Commands look the spec up via [forProjectType] and
/// never branch on the language themselves. The shape mirrors `gg_lang`'s
/// `catalog.spec(type)` so the data can move into the language catalog later
/// without touching call sites.
class VersionFileSpec {
  /// Constructor.
  const VersionFileSpec({
    required this.sourceDir,
    required this.sourceExtension,
    required this.testSuffix,
    required this.testImport,
    required this.isDart,
    this.legacyTestSuffix,
    this.testDir = 'test',
  });

  // ...........................................................................
  /// The spec for [type] as laid out in [directory], or null when no version
  /// file of that language belongs there.
  ///
  /// Dart and Flutter packages always use the fixed [dartSpec] and
  /// [flutterSpec]. TypeScript follows the package: see [typeScriptSpecFor].
  static VersionFileSpec? forDirectory(ProjectType type, Directory directory) =>
      type == ProjectType.typescript
      ? typeScriptSpecFor(directory)
      : forProjectType(type);

  // ...........................................................................
  /// The TypeScript spec for the package in [directory], or null when the
  /// package has no TypeScript code.
  ///
  /// - A hybrid without `tsconfig.json` ships its npm package without any
  ///   TypeScript (the DNA packages), so it gets no TypeScript version file.
  /// - The version file goes to the `rootDir` of `tsconfig.json`, `src` when
  ///   none is set. A bridge keeps its code in `typescript/`.
  /// - The mirror test goes to `<rootDir>/test` when that folder exists, to
  ///   `test` otherwise.
  /// - The mirror test ends in `.test.ts` when the tests next to it all do,
  ///   in `.spec.ts` otherwise, so the vitest `include` of the package picks
  ///   it up.
  static VersionFileSpec? typeScriptSpecFor(Directory directory) {
    final tsconfig = File(join(directory.path, 'tsconfig.json'));
    if (!tsconfig.existsSync()) {
      return isHybridProject(directory) ? null : typeScriptSpec;
    }

    final sourceDir = _rootDirOf(tsconfig) ?? typeScriptSpec.sourceDir;
    final nestedTests = '$sourceDir/test';
    final testDir =
        Directory(join(directory.path, joinAll(nestedTests.split('/'))))
            .existsSync()
        ? nestedTests
        : typeScriptSpec.testDir;

    return typeScriptSpec._copyWith(
      sourceDir: sourceDir,
      testDir: testDir,
      testSuffix: _testSuffixIn(
        Directory(join(directory.path, joinAll(testDir.split('/')))),
      ),
    );
  }

  // ...........................................................................
  /// Every place a TypeScript version file or mirror test for [slug] was
  /// ever written to inside [directory], whatever the current layout.
  ///
  /// Older gg versions always used `src/` and `test/`, and named the mirror
  /// test `.test.ts`. The writer deletes each of these that it generated and
  /// that is not a target of the current layout.
  static List<File> typeScriptLocations(Directory directory, String slug) {
    final spec = typeScriptSpecFor(directory) ?? typeScriptSpec;
    final sourceDirs = {typeScriptSpec.sourceDir, spec.sourceDir};
    final testDirs = {typeScriptSpec.testDir, spec.testDir};
    const suffixes = [_specSuffix, _testTsSuffix];

    return [
      for (final dir in sourceDirs) '$dir/${slug}_version.ts',
      for (final dir in testDirs)
        for (final suffix in suffixes) '$dir/$slug$suffix',
    ].map((p) => File(join(directory.path, joinAll(p.split('/'))))).toList();
  }

  // ...........................................................................
  /// The spec for [type], or null when [type] has no manifest to read a
  /// version from.
  static VersionFileSpec? forProjectType(ProjectType type) => switch (type) {
    ProjectType.dart => dartSpec,
    ProjectType.flutter => flutterSpec,
    ProjectType.typescript => typeScriptSpec,
    ProjectType.none => null,
  };

  // ...........................................................................
  /// The spec for plain Dart packages.
  static const VersionFileSpec dartSpec = VersionFileSpec(
    sourceDir: 'lib/src',
    sourceExtension: 'dart',
    testSuffix: '_version_test.dart',
    testImport: 'package:test/test.dart',
    isDart: true,
  );

  // ...........................................................................
  /// The spec for Flutter packages.
  ///
  /// Identical to [dartSpec] except for the test import: `package:test` is not
  /// in the resolved dependency closure of a Flutter package, so a mirror test
  /// importing it would not compile.
  static const VersionFileSpec flutterSpec = VersionFileSpec(
    sourceDir: 'lib/src',
    sourceExtension: 'dart',
    testSuffix: '_version_test.dart',
    testImport: 'package:flutter_test/flutter_test.dart',
    isDart: true,
  );

  // ...........................................................................
  /// The spec for TypeScript packages.
  static const VersionFileSpec typeScriptSpec = VersionFileSpec(
    sourceDir: 'src',
    sourceExtension: 'ts',
    testSuffix: _specSuffix,
    testImport: 'vitest',
    isDart: false,
    legacyTestSuffix: _testTsSuffix,
  );

  /// The directory holding the version file, relative to the package root.
  final String sourceDir;

  /// The extension of the version file, without the dot.
  final String sourceExtension;

  /// The suffix appended to the slug to form the mirror test file name.
  final String testSuffix;

  /// The import the mirror test needs for its test framework.
  final String testImport;

  /// The suffix an older gg used for the mirror test, or null when the name
  /// never changed.
  ///
  /// TypeScript mirror tests used to end in `.test.ts`, which vitest configs
  /// that only include `*.spec.ts` never run. A generated test found under the
  /// old name is replaced by one under the new name.
  final String? legacyTestSuffix;

  /// Whether this spec describes a Dart-family package.
  final bool isDart;

  /// The directory holding the mirror test, relative to the package root.
  final String testDir;

  // ...........................................................................
  /// The version file path for [slug], relative to the package root, always
  /// with forward slashes so it can be embedded in generated source.
  String sourcePath(String slug) =>
      '$sourceDir/${slug}_version.$sourceExtension';

  // ...........................................................................
  /// The mirror test path for [slug], relative to the package root, always
  /// with forward slashes.
  String testPath(String slug) => '$testDir/$slug$testSuffix';

  // ...........................................................................
  /// The mirror test file of an older gg inside [directory], or null when
  /// this spec has no [legacyTestSuffix].
  File? legacyTestFile(Directory directory, String slug) =>
      legacyTestSuffix == null
      ? null
      : File(join(directory.path, 'test', '$slug$legacyTestSuffix'));

  // ...........................................................................
  /// The version file inside [directory].
  File sourceFile(Directory directory, String slug) =>
      File(join(directory.path, joinAll(sourcePath(slug).split('/'))));

  // ...........................................................................
  /// The mirror test file inside [directory].
  File testFile(Directory directory, String slug) =>
      File(join(directory.path, joinAll(testPath(slug).split('/'))));

  // ...........................................................................
  /// The declaration prefix the mirror test searches for and rewrites.
  ///
  /// Everything up to and including the `= `, so the version literal is the
  /// only part that ever changes. Contains no regular-expression
  /// metacharacters, because a slug is `[a-z0-9_]+` by construction.
  String declaration(String slug) => isDart
      ? 'const String ${versionFileIdentifier(slug)} = '
      : 'export const ${versionFileIdentifier(slug)} = ';

  // ...........................................................................
  /// Renders the version file for [slug] at [version].
  ///
  /// The body is deliberately free of any `(...)` followed by `{` or `=>`, so
  /// `gg_test`'s `hasFunctions` predicate reports the file as function-free and
  /// exempts it from the untested-file check. Only the version literal varies
  /// between releases, so the rendered line count is stable.
  String renderSource({
    required String slug,
    required String version,
    required String packageName,
  }) => _fill(isDart ? _dartSourceTemplate : _typeScriptSourceTemplate, {
    'HEADER': _header,
    'MARKER': versionFileMarker,
    'TEST_PATH': testPath(slug),
    'PACKAGE': packageName,
    'DECL': declaration(slug),
    'VERSION': version,
  });

  // ...........................................................................
  /// Renders the self-healing mirror test for [slug].
  ///
  /// The test reads the version from [manifestFile], and when the version file
  /// disagrees it rewrites only the version literal and passes. It never fails
  /// on drift. Its content does not depend on the version, so it stays
  /// byte-stable across releases.
  ///
  /// The Dart variant deliberately does not import the package barrel: a
  /// package that acquires its version file during publishing has no export
  /// for it yet, and a const-only file is exempt from the coverage check
  /// anyway. The TypeScript variant must import the constant, because every
  /// gg-managed TypeScript project reports `src/**` coverage against a 100%
  /// threshold.
  String renderTest({required String slug, required String manifestFile}) =>
      _fill(isDart ? _dartTestTemplate : _typeScriptTestTemplate, {
        'HEADER': _header,
        'MARKER': versionFileMarker,
        'TEST_IMPORT': testImport,
        'SOURCE': sourcePath(slug),
        'SOURCE_IMPORT': _sourceImport(slug),
        'MANIFEST': manifestFile,
        'SLUG': slug,
        'ID': versionFileIdentifier(slug),
        'DECL': declaration(slug),
        'EXT': sourceExtension,
      });

  // ######################
  // Private
  // ######################

  // ...........................................................................
  /// The header block prefixed to generated Dart files, empty for TypeScript.
  String get _header => isDart ? '$versionFileLicenseHeader\n\n' : '';

  // ...........................................................................
  static const String _specSuffix = '_version.spec.ts';
  static const String _testTsSuffix = '_version.test.ts';

  // ...........................................................................
  VersionFileSpec _copyWith({
    required String sourceDir,
    required String testDir,
    required String testSuffix,
  }) => VersionFileSpec(
    sourceDir: sourceDir,
    sourceExtension: sourceExtension,
    testSuffix: testSuffix,
    testImport: testImport,
    isDart: isDart,
    legacyTestSuffix: legacyTestSuffix,
    testDir: testDir,
  );

  // ...........................................................................
  /// The import specifier of the version file, relative to the mirror test.
  String _sourceImport(String slug) {
    final target = '$sourceDir/${slug}_version';
    final relative = posix.relative(target, from: testDir);
    return relative.startsWith('.') ? relative : './$relative';
  }

  // ...........................................................................
  /// The `compilerOptions.rootDir` of [tsconfig], or null when it sets none or
  /// points at the package root.
  ///
  /// Read with a pattern instead of a JSON parser: `tsconfig.json` allows
  /// comments and trailing commas, which `jsonDecode` rejects.
  static String? _rootDirOf(File tsconfig) {
    final match = RegExp(r'"rootDir"\s*:\s*"([^"]*)"')
        .firstMatch(tsconfig.readAsStringSync());

    var dir = match?.group(1)?.trim() ?? '';
    if (dir.startsWith('./')) {
      dir = dir.substring(2);
    }
    dir = dir.replaceAll(RegExp(r'/+$'), '');

    return dir.isEmpty || dir == '.' ? null : dir;
  }

  // ...........................................................................
  /// `.test.ts` when every test in [testDir] ends in `.test.ts`, `.spec.ts`
  /// otherwise.
  ///
  /// Generated mirror tests are left out: an old `.test.ts` one must not keep
  /// the package on `.test.ts` forever.
  static String _testSuffixIn(Directory testDir) {
    if (!testDir.existsSync()) {
      return _specSuffix;
    }

    final names = testDir
        .listSync(recursive: true)
        .whereType<File>()
        .map((f) => basename(f.path))
        .where((n) => !n.endsWith(_specSuffix) && !n.endsWith(_testTsSuffix))
        .toList();

    final hasTest = names.any((n) => n.endsWith('.test.ts'));
    final hasSpec = names.any((n) => n.endsWith('.spec.ts'));

    return hasTest && !hasSpec ? _testTsSuffix : _specSuffix;
  }

  // ...........................................................................
  static String _fill(String template, Map<String, String> values) {
    var result = template;
    for (final entry in values.entries) {
      result = result.replaceAll('{{${entry.key}}}', entry.value);
    }
    return result;
  }

  // ...........................................................................
  static const String _dartSourceTemplate =
      '{{HEADER}}'
      '// {{MARKER}} - DO NOT EDIT.\n'
      '// Kept in sync by {{TEST_PATH}}.\n'
      '// coverage:ignore-file\n'
      '\n'
      '/// The version of the `{{PACKAGE}}` package.\n'
      "{{DECL}}'{{VERSION}}';\n";

  // ...........................................................................
  static const String _typeScriptSourceTemplate =
      '{{HEADER}}'
      '// {{MARKER}} - DO NOT EDIT.\n'
      '// Kept in sync by {{TEST_PATH}}.\n'
      '\n'
      '/** The version of the `{{PACKAGE}}` package. */\n'
      "{{DECL}}'{{VERSION}}';\n";

  // ...........................................................................
  static const String _dartTestTemplate = r'''
{{HEADER}}import 'dart:io';

import '{{TEST_IMPORT}}';

// {{MARKER}} - DO NOT EDIT.
//
// Repairs the version literal in
// {{SOURCE}}
// when it drifts from {{MANIFEST}}. Drift is not an error here: the literal
// is rewritten and the test passes.

void main() {
  group('{{SLUG}}_version.{{EXT}}', () {
    test('matches the version in {{MANIFEST}}', () {
      const declaration = '{{DECL}}';
      final match = RegExp(
        r'^version:\s*(\S+)\s*$',
        multiLine: true,
      ).firstMatch(File('{{MANIFEST}}').readAsStringSync());
      expect(match, isNotNull, reason: 'no version in {{MANIFEST}}');

      final expected = "$declaration'${match!.group(1)}';";
      final file = File('{{SOURCE}}');

      if (!file.readAsStringSync().contains(expected)) {
        file.writeAsStringSync(
          file.readAsStringSync().replaceFirst(
            RegExp("$declaration'[^']*';"),
            expected,
          ),
        );
      }

      expect(file.readAsStringSync(), contains(expected));
    });
  });
}
''';

  // ...........................................................................
  static const String _typeScriptTestTemplate = r'''
import { readFileSync, writeFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import { {{ID}} } from '{{SOURCE_IMPORT}}';

// {{MARKER}} - DO NOT EDIT.
//
// Repairs the version literal in
// {{SOURCE}}
// when it drifts from {{MANIFEST}}. Drift is not an error here: the literal
// is rewritten and the test passes.

describe('{{SLUG}}_version.{{EXT}}', () => {
  it('matches the version in {{MANIFEST}}', () => {
    const manifest = JSON.parse(
      readFileSync('{{MANIFEST}}', 'utf8'),
    ) as { version?: string };
    expect(manifest.version).toBeTruthy();

    const declaration = '{{DECL}}';
    const expected = `${declaration}'${manifest.version}';`;
    const path = '{{SOURCE}}';

    if (!readFileSync(path, 'utf8').includes(expected)) {
      writeFileSync(
        path,
        readFileSync(path, 'utf8').replace(
          new RegExp(`${declaration}'[^']*';`),
          expected,
        ),
      );
    }

    expect(readFileSync(path, 'utf8')).toContain(expected);
    expect({{ID}}).toBeTruthy();
  });
});
''';
}
